[package]
name = "pdftool"
version = "0.1.0"
edition = "2024"
default-run = "pdftool-gui"

[dependencies]
clap = { version = "4.6.7", features = ["derive"] }
eframe = "0.33.3"
lopdf = "0.45.0"
rfd = "0.17.2"


[[bin]]
name = "pdftool"
path = "src/main.rs"

[[bin]]
name = "pdftool-gui"
path = "src/bin/pdftool-gui/main.rs"
